### ISSUE TITLE
Question: Fresco implementation plans?

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/nativescript-fresco#1]
Is it planned to implement all that Fresco offers? Also publishing on npm?

**Comment by VladimirAmiorkov** [comment]
Hi @bradmartin ,

Yes there were plans for future improvements and implementations of the Fresco features in the nativescript plugin. With the **1.0.0** version we have introduced most of the features available in the library and it is already published on npm, you can find it [here](https://www.npmjs.com/package/nativescript-fresco) or simply do `tns plugin add nativescript-fresco`.
