### ISSUE TITLE
[Question] frescoModule.shutDown === undefined?

### ISSUE THREAD

**Issue by anki247** [NativeScript/nativescript-fresco#107]
I am using Angular+NS and in the index.d.ts there is no definition of `shutDown()`.

````typescript
import * as frescoModule from "nativescript-fresco";
console.log('--> ', (frescoModule as any).shutDown); // --> undefined
````

**Comment by VladimirAmiorkov** [comment]
Hi,

Please refer [this](https://github.com/NativeScript/nativescript-fresco#manually-shut-down-the-native-fresco-library) section from the readme regarding the shutDown functionality. Also make sure that you are running the above code on Android, this plugin does not support the iOS framework and its implementation on it is empty.
