### ISSUE TITLE
README not complete?

### ISSUE THREAD

**Issue by anki247** [NativeScript/nativescript-fresco#108]
In section "**Cache**"

> The nativescript-fresco {N} plugin has built-in cache mechanism which handles managing the images in the memory. There are two types of cache mechanisms `memory` and `disk`, you can manually manage both of them with the following functionality. 

Which following functionality?

**Comment by elena-p** [comment]
Hi @anki247,

The following sections describe the different ways you can affect the build-in fresco cache mechanism:

- ['Refresh' the 'imageUri'](https://github.com/NativeScript/nativescript-fresco#refresh-the-imageuri)
- [Clear everything from the cache](https://github.com/NativeScript/nativescript-fresco#clear-everything-from-the-cache)
- [Evict all images with a specific URI from the cache](https://github.com/NativeScript/nativescript-fresco#evict-all-images-with-a-specific-uri-from-the-cache)

**Comment by anki247** [comment]
[close]
