### ISSUE TITLE
Images not loaded or loading too slow 

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/nativescript-fresco#11]
Happens on on HTC one mini 2 - Android 4.4.2. Works well on Nexus 7 (Android 6.0.1)
See it in SDK Examples - ListView -> Item Layouts -> Linear/Grid
https://github.com/telerik/nativescript-ui-samples 

```
"nativescript": {
        "id": "org.nativescript.sdk",
        "tns-android": {
            "version": "2.1.1"
        },
        "tns-ios": {
            "version": "2.1.0"
        }
    },
    "dependencies": {
        "nativescript-fresco": "^1.0.3",
        "nativescript-telerik-ui-pro": "1.2.0",
        "tns-core-modules": "2.1.0"
    },
    "devDependencies": {
        "babel-traverse": "6.9.0",
        "babel-types": "6.9.0",
        "babylon": "6.8.0",
        "filewalker": "0.1.2",
        "lazy": "1.0.11",
        "nativescript-dev-typescript": "^0.3.2",
        "typescript": "^1.8.10"
    }
```

**Comment by VladimirAmiorkov** [comment]
A quick update on the issue.

The issues reproduced when setting the `imageUri` to {N} resoruce files. For example like so: `imageUri="res://myImage"`

**Comment by 9thwall** [comment]
Looks like this is an old and closed issue but I'm currently having this issue only when loading images from res://image.  I'm using {N} with Angular

**Comment by VladimirAmiorkov** [comment]
@9thwall are you using the latest 1.0.12 version of the plugin. If so can you also try to reproduce it with the previous 1.0.11.

In order to install a specific version simply do:

`tns plugin add nativescript-fresco@1.0.11`

If you continue to experience this issue can you give me some more information regarding your application. A runnable project or code snippets would be great help.

**Comment by 9thwall** [comment]
Hi Vladimir, 
I had 1.0.11 installed. I upgraded to 1.0.12 and the issue still exists. 

If this is suppose to work I'm assuming this is most likely something simple I am doing wrong. 

My code is like this.. 
`<FrescoDrawee #avatar [imageUri]="user.picurl" row="0" col="0" backgroundUri="~/images/placeholder-avatar.jpg" roundAsCircle="true" width="38" height="38"></FrescoDrawee>`

I console.log `user.picurl` and sure enough it's showing the correct image link.  

Strange thing is that even if I hard code the link in like this.. 
`<FrescoDrawee #avatar imageUri="res://me" row="0" col="0" backgroundUri="~/images/placeholder-avatar.jpg" roundAsCircle="true" width="38" height="38"></FrescoDrawee>`

It still doesn't show the image.
I should mention that I really do have the image named "me.png" and I hope there isn't any restrictions on using short image names.

**Comment by 9thwall** [comment]
Sorry about this.. hard coding the value directly like `imageUri="res://me"` does show the image. 
Only when the value is set dynamically like `[imageUri]="user.picurl"` or `imageUri="{{user.picurl}}"` it doesn't show.

Does it matter that I am switching the url of user.picurl conditionally from local to http dynamically?
What I mean is, depending on a condition, user.picurl can be "http://myserver.com/images/userpic.png" or "res://me". Can this be a problem?

**Comment by 9thwall** [comment]
Geez... Nevermind. 
It's working.... It was my bad code. Sorry to bug you about this...
