### ISSUE TITLE
onRelease called when .get() is null

### ISSUE THREAD

**Issue by Ivshti** [NativeScript/nativescript-fresco#12]
When stacking RadListView inside a ListView (for the purpose of having multiple rows, with multiple columns, scrollable separately, but all images loaded dynamically when in-view: like Netflix), it sometimes happens that `onRelease` can get called when `.get()` is null

Here's an example stack trace:

```
com.tns.NativeScriptException: 
Calling js method onRelease failed

TypeError: Cannot read property 'notify' of null
File: \"/data/data/org.nativescript.stremio/files/app/tns_modules/nativescript-fresco/nativescript-fresco.js, line: 282, column: 34

StackTrace: 

Frame: function:'com.facebook.drawee.controller.ControllerListener.onRelease', file:'/data/data/org.nativescript.stremio/files/app/tns_modules/nativescript-fresco/nativescript-fresco.js', line: 282, column: 35



at com.tns.Runtime.callJSMethodNative(Native Method)

at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)

at com.tns.Runtime.callJSMethodImpl(Runtime.java:726)

at com.tns.Runtime.callJSMethod(Runtime.java:712)

at com.tns.Runtime.callJSMethod(Runtime.java:693)

at com.tns.Runtime.callJSMethod(Runtime.java:683)

at com.tns.gen.com.facebook.drawee.controller.ControllerListener.onRelease(ControllerListener.java:47)

at com.facebook.drawee.controller.AbstractDraweeController.releaseFetch(AbstractDraweeController.java:188)

at com.facebook.drawee.controller.AbstractDraweeController.release(AbstractDraweeController.java:167)

at com.facebook.drawee.components.DeferredReleaser$1.run(DeferredReleaser.java:67)

at android.os.Handler.handleCallback(Handler.java:739)

at android.os.Handler.dispatchMessage(Handler.java:95)

at android.os.Looper.loop(Looper.java:135)

at android.app.ActivityThread.main(ActivityThread.java:5257)

at java.lang.reflect.Method.invoke(Native Method)

at java.lang.reflect.Method.invoke(Method.java:372)

at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

```

**Comment by VladimirAmiorkov** [comment]
Hi @Ivshti ,

Hmm that is interesting. The `that` is an `WeakRef` which by design should not be GC if it can still be accessed. I will take a look at this nested scenario and see what could be done to resolve such possible issues. Thanks.

**Comment by Ivshti** [comment]
I doubt that you'll be able to reproduce it easily, as we managed to do it only when they are many components. Our UI is complex by design, somewhat similar to YouTube's UI of popular channels and their videos (scrolling vertically rows, and horizontally within them)

can't we just add a check in every method using .get()? or potentially a more elegant way to handle the case

**Comment by VladimirAmiorkov** [comment]
@Ivshti indeed adding a NullRef check would be part of the solution but I have my concerns about what might be causing this issue in the first place. As mentioned the `WeakRef` should not be GC therefore its `.get()` method should be present. Simply adding the check would lead to a scenario the native Android Fresco's `Release` event would have been raised but the {N} onRelease event would not be as it is raised by the WeakRef.

**Comment by VladimirAmiorkov** [comment]
@Ivshti Could you share with me some code snippets or at least the structure of the layout and where exactly the FrescoDrawee instances are located? Feel free to use pseudocode if you like.

**Comment by Ivshti** [comment]
```
<GridLayout
    rows="*"
    id="board"
    loaded="pageLoaded"
    xmlns:lv="nativescript-telerik-ui/listview"
    xmlns:nativescript-fresco="nativescript-fresco">

    <ListView items="{{ groups }}" >        
        <ListView.itemTemplate>
            <StackLayout>
              <Label class="boardLabel" text="{{ displayName }}"/>

              <lv:RadListView
                itemTap="{{ $parents['ListView'].openDetail }}"
                items="{{ notifs }}"
                visibility="{{ notifs ? 'visible' : 'collapse' }}"
                loaded="listLoaded"
                unloaded="listUnloaded">
                <lv:RadListView.listViewLayout>
                  <lv:ListViewGridLayout scrollDirection="Horizontal" spanCount="1"/>
                </lv:RadListView.listViewLayout>

                <lv:RadListView.itemTemplate>
                  <GridLayout
                    width="{{$parents['ListView'].itemWidth}}">
                      <android>
                        <GridLayout rows= "*">
                          <nativescript-fresco:FrescoDrawee
                            row="0"
                            id="{{ _id }}"
                            imageUri="{{ backgroundImage }}"
                            stretch="aspectFill"
                            height="{{ $parents['ListView'].itemWidth, $parents['StackLayout'].itemHeight }}" />
                          <Label
                            row="0"
                            text="{{ title }}"
                            cssClass="itemName"
                            horizontalAlignment="center"
                            verticalAlignment="center"
                            visibility="{{ visible }}"
                            verticalAlignment="bottom"
                            horizontalAlignment="stretch"
                            textWrap="true"/>
                        </GridLayout>
                      </android>

                      <iOS>
                          <Image class="item"
                            id="{{ _id }}"
                            src="{{ background }}"
                            stretch="aspectFill"/>
                      </iOS>
                  </GridLayout>
                </lv:RadListView.itemTemplate>
              </lv:RadListView>

              <lv:RadListView
                itemTap="{{ $parents['ListView'].openDetail }}"
                items="{{ items }}"
                visibility="{{ items ? 'visible' : 'collapse' }}"
                loaded="listLoaded"
                unloaded="listUnloaded">
                <lv:RadListView.listViewLayout>
                  <lv:ListViewGridLayout scrollDirection="Horizontal" spanCount="1"/>
                </lv:RadListView.listViewLayout>

                <lv:RadListView.itemTemplate>
                  <GridLayout
                    width="{{$parents['ListView'].itemWidth}}">
                      <android>
                        <GridLayout rows= "*">                          
                          <nativescript-fresco:FrescoDrawee
                            row="0"
                            id="{{ _id }}"
                            imageUri="{{ backgroundImage }}"
                            stretch="aspectFill"
                            height="{{ $parents['ListView'].itemWidth, $parents['ListView'].itemHeight }}" />

                            <GridLayout columns="20, *" horizontalAlignment="center" verticalAlignment="bottom" visibility="{{ inCinema ? 'visible' : 'collapse' }}">
                              <Image col="0" src="~/images/icon-yellow-star.png" stretch="none" cssClass="btnStarImg"/>
                              <Label col="1" text="{{ inCinemaLabel }}" cssClass="inCinema"/>
                            </GridLayout>
                        </GridLayout>
                      </android>

                      <iOS>
                          <Image class="item"
                            id="{{ _id }}"
                            src="{{ backgroundImage }}"
                            stretch="aspectFill"/>
                      </iOS>
                  </GridLayout>
                </lv:RadListView.itemTemplate>
              </lv:RadListView>              
          </StackLayout>
        </ListView.itemTemplate>
     </ListView>

    <ActivityIndicator width="100" height="100" busy="{{ isLoading }}" />
</GridLayout>
```

This is the whole layout. It's inside a TabView

I could provide sample data, it would take some time, but I am kind of doubtful it would help you. I've only seen this crash twice, and I use/test/develop the app often

---

Is it possible that something deliberately frees the object?

**Comment by Ivshti** [comment]
awesome, cheers!

**Comment by Daxito** [comment]
**I am getting this error also (and not always), I am using version 1.012, is there a workaround?**


com.tns.NativeScriptException: 
Calling js method onRelease failed

TypeError: Cannot read property 'notify' of null
File: "/data/data/ddddddd/files/app/tns_modules/nativescript-fresco/nativescript-fresco.js, line: 370, column: 38

StackTrace: 
Frame: function:'com.facebook.drawee.controller.ControllerListener.onRelease', file:'/data/data/ddddd/files/app/tns_modules/nativescript-fresco/nativescript-fresco.js', line: 370, column: 39


at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:865)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:730)
at com.tns.Runtime.callJSMethod(Runtime.java:716)
at com.tns.Runtime.callJSMethod(Runtime.java:697)
at com.tns.Runtime.callJSMethod(Runtime.java:687)
at com.tns.gen.com.facebook.drawee.controller.ControllerListener.onRelease(com.facebook.drawee.controller.ControllerListener.java)
at com.facebook.drawee.controller.AbstractDraweeController.releaseFetch(AbstractDraweeController.java:188)
at com.facebook.drawee.controller.AbstractDraweeController.release(AbstractDraweeController.java:167)
at com.facebook.drawee.components.DeferredReleaser$1.run(DeferredReleaser.java:67)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by VladimirAmiorkov** [comment]
@Daxito For a quick workaround you can edit the mentioed 370 row to:

```
if (that.get()) {
    that.get().notify(args);
}
```

but can you share with me the scenario in which you are getting this error because the `that.get()` should never be undefined and I haven't been able to reproduce the issue from this tread on my side.

**Comment by Daxito** [comment]
@VladimirAmiorkov Thank you for the workaround. 
This is not an issue I can duplicate easy either (I hate those), basically I have my Fresco Image tag inside of a RadListView like this: 
[frescoTag.txt](https://github.com/NativeScript/nativescript-fresco/files/617276/frescoTag.txt)

I populate the "images" collection using the "set" (since this is not an observable collection) every time I select a picture from the gallery:

 this.set('images',newArrayWithNewImages);

I know this is not an easy to fix issue, can just create a pull request and add the workaround you mentioned?

**Comment by Daxito** [comment]
I was able to duplicate this issue using the attached App, just run it, and then tap on the button until it crashes, it crashed for me when I was like 33 taps left like 3 or more times, it is not consistent, so maybe you will have to run the app a couple of times before you are lucky and it crashes.

This code is similar to what I have, btw.

[frescoBug.zip](https://github.com/NativeScript/nativescript-fresco/files/617738/frescoBug.zip)

**Comment by VladimirAmiorkov** [comment]
Hi @Daxito ,

Thank you for the additional details and project. Unfortunately I am still unable to reproduce this issue, I have ran the app for 30 minutes with no exception, never the least I implemented a "bind fix" for it that should cover all of the cases regarding "undefined" objects when raising the plugin events. It looks like the native Android Fresco library might by making something behind the doors that clears the `SimpleDraweeView` objects leading to this exception.

I updated the npm package and you should be able to get the **1.0.13** version.

**Comment by Daxito** [comment]
I was using a Samsum Galaxy S5 with android 6.0.1, not sure if that matters, but anyway, thank you for you quick response! I am updating right now.
