### ISSUE TITLE
Make the plugin compatible with Angular 2 out of the box 

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-fresco#17]
Currently you need to manually register the "FrescoDrawee" tag with the `nativescript-angular/element-registry` like so:

```
import * as elementRegistryModule from 'nativescript-angular/element-registry';

elementRegistryModule.registerElement("FrescoDrawee", () => frescoModule.FrescoDrawee);
```

**Comment by karan1149** [comment]
Where are we doing this registration? In main.ts before calling bootstrap?

**Comment by VladimirAmiorkov** [comment]
@karan1149 yes before you call the `.bootstrapModule(...);` function, like [this](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/app.module.ts#L31).
