### ISSUE TITLE
Getting a Typescript error setting up with Angular

### ISSUE THREAD

**Issue by 9thwall** [NativeScript/nativescript-fresco#21]
Hi! 
I'm falling the example here:
[https://github.com/NativeScript/nativescript-fresco/blob/master/demo/app/app.module.ts#L23](https://github.com/NativeScript/nativescript-fresco/blob/master/demo/app/app.module.ts#L23)

and then I'm getting an error 

> Left hand side of assignment expression cannot be a constant or a read only property

when I add this..

```
if (applicationModule.android) {
    applicationModule.onLaunch = function (intent) {
        frescoModule.initialize();
    };
}
```

I double checked to make sure I'm adding all the imports as shown... 
What can be causing this?

**Comment by 9thwall** [comment]
I read this.. 
[http://stackoverflow.com/questions/38818475/left-hand-side-of-assignment-expression-cannot-be-a-constant-or-a-read-only-prop](http://stackoverflow.com/questions/38818475/left-hand-side-of-assignment-expression-cannot-be-a-constant-or-a-read-only-prop)

so I edited the code to this.. 

```
if (applicationModule.android) {
    (applicationModule as any).onLaunch = function (intent) {
        frescoModule.initialize();
    };
}
```

and that removed the TypeScript angry red line. But then now when I load the app. I get this..

> java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
> 
> Error calling module function
> 
> Error calling module function
> 
> Error calling module function
> 
> TypeError: Cannot read property 'animated' of undefined
> File: "/data/data/org.nativescript.app/files/app/tns_modules/nativescript-fresco/nativescript-fresco.js, line: 85, column: 28
> 
> StackTrace:
> Frame: function:'', file:'/data/data/org.nativescript.app/files/app/tns_modules/nativescript-fresco/nativescript-fresco.js', line: 85, column: 29
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.app/files/app/tns_modules/nativescript-fresco/angular/nativescript-fresco-directives.js', line: 13, column: 29
> Frame: function:'require', file:'', line: 1, column: 266
> Frame: function:'', file:'/data/data/org.nativescript.app/files/app/main.js', line: 6, column: 17
> Frame: function:'require', file:'', line: 1, column: 266
> 
> TypeError: Cannot read property 'animated' of undefined
> File: "<unknown>, line: 1, column: 265

**Comment by VladimirAmiorkov** [comment]
Hi @9thwall ,

It looks like you are using the latest version of VS Code 1.6.x which had a bundled 2.3.0 TypeScript in it. In the 2.0.3 version of TypeScript the mentioned association of a function to an event (".onLaunch = function (intent)") is treated as an error. I have migrated the demo application to use the latest version of TypeScript and have resolved the mentioned onLaunch association.

Simply change the initialization of Fresco to this:

```
if (applicationModule.android) {
    applicationModule.on("launch", () => {
        frescoModule.initialize();
    });
}
```
