### ISSUE TITLE
Question about best practice for IOS

### ISSUE THREAD

**Issue by 9thwall** [NativeScript/nativescript-fresco#23]
Hi! Thank you for this amazing plug in. 
It's solves so many issues for my app. 

I was wondering what other developers use when developing for IOS. 
I mean, I now have these <FrescoDrawee></FrescoDrawee> tags for all the images for android. But what do you do when you are ready to develop for IOS? Do I need to have *ngIF statements on all of them for android and use default Image tags for IOS? What are other developers doing to replace Fresco?

**Comment by jboeijenga** [comment]
+1

**Comment by bradmartin** [comment]
``` XML
 <android>
         <fresco:FrescoDrawee row="2" col="1" imageUri="{{ loadingImage }}" aspectRatio="1" actualImageScaleType="center" />
   </android>
   <ios>
        <Image row="2" col="1" src="{{ loadingImage }}" class="center" stretch="aspectFit" />
   </ios>
```

One approach.

**Comment by 9thwall** [comment]
Thank you for the help Brad. 
I ended up posting on [Stackoverflow ](http://stackoverflow.com/questions/40322575/best-practice-for-loading-images-on-nativescript-angular-ios) and received a very similar answer. 
I should of closed this. Completely slipped my mind.
