### ISSUE TITLE
Fresco package issue

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/nativescript-fresco#26]
See the image: 
![snip20161203_1](https://cloud.githubusercontent.com/assets/6006148/20863917/1ce1a0a4-b9a2-11e6-8674-5b26194475c2.png)

Any reason that's happening? I'm going through plugins to remove junk for release builds and stumbled on that today. I know it's not needed so I remove but  just FYI it's happening and I didn't think it was right so curious if I'm missing something 😄

**Comment by VladimirAmiorkov** [comment]
Hi @bradmartin ,

Hmm I am not sure what may be causing this issue other than some faulty runs of the "demo" app  during development that have made their way to the published package. I have removed those files and upload a new version **1.0.14** to npm.

Thank you for reporting this.
