### ISSUE TITLE
Nativescript 3.0 failed to find module ui/core/proxy

### ISSUE THREAD

**Issue by dgomezs** [NativeScript/nativescript-fresco#36]
hi there, 

I'm in the process of upgrading my app to Nativescript 3.0 rc and run into this issue. It seems the ui/core/proxy module has been removed and nativescript-fresco is using it. Any plans to update the module to make it compatible with Nativescript 3.0?

Thank you very much in advanced.

**Comment by VladimirAmiorkov** [comment]
Hi @dgomezs 

I just published the migrated plugin for {N} 3.0 to npmjs.com. Simply upgrade your package.json to point to `"nativescript-fresco": "^3.0.2"

**Comment by dgomezs** [comment]
Thanks. Looking forward to testing it

**Comment by HemantSPawar** [comment]
1.remove platform,hooks,node modules folder
2.npm cache clean
3.npm install nativescript@next
4.npm install
5.tns run android

done.Thanks.
