### ISSUE TITLE
Can't build the demo app

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/nativescript-fresco#41]
I wanted to see the demo app in action, but it doesn't build. Might be something missing on my end here. I have no problem building Telerik's NS UI app or my own stuff. I don't use Angular though, but I would expect the demo app to install dependencies.

mini:Projects sergei$ git clone https://github.com/NativeScript/nativescript-fresco.git
Cloning into 'nativescript-fresco'...
remote: Counting objects: 794, done.
remote: Total 794 (delta 0), reused 0 (delta 0), pack-reused 794
Receiving objects: 100% (794/794), 4.15 MiB | 4.00 MiB/s, done.
Resolving deltas: 100% (427/427), done.
mini:Projects sergei$ cd nativescript-fresco/demo/
mini:demo sergei$ tns run android
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

nativescript-fresco@3.0.2 prepublish /Users/sergei/Projects/nativescript-fresco
npm run ngc

nativescript-fresco@3.0.2 ngc /Users/sergei/Projects/nativescript-fresco
ngc

sh: ngc: command not found

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node@6/6.10.3/bin/node" "/usr/local/bin/npm" "run" "ngc"
npm ERR! node v6.10.3
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! nativescript-fresco@3.0.2 ngc: `ngc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the nativescript-fresco@3.0.2 ngc script 'ngc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nativescript-fresco package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ngc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nativescript-fresco
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nativescript-fresco
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sergei/.npm/_logs/2017-06-03T21_26_54_620Z-debug.log
npm ERR! addLocal Could not install /Users/sergei/Projects/nativescript-fresco
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node@6/6.10.3/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.10.3
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! nativescript-fresco@3.0.2 prepublish: `npm run ngc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nativescript-fresco@3.0.2 prepublish script 'npm run ngc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nativescript-fresco package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run ngc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nativescript-fresco
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nativescript-fresco
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sergei/.npm/_logs/2017-06-03T21_26_59_527Z-debug.log
Unable to install dependencies. Make sure your package.json is valid and all dependencies are correct. Error is: Command npm failed with exit code 1
mini:demo sergei$

**Comment by VladimirAmiorkov** [comment]
If you are building ​the plugin from the source code itself make sure to execute "npm install" first, this will download the required dependencies for the angular AoT compiler that is executed from the prepublish script.

**Comment by sserdyuk** [comment]
I am building the demo app, not the plugin intself. I actually tried `npm install` and `tns install`, all fail with the exact message as above.

**Comment by VladimirAmiorkov** [comment]
Please refer to [this](https://github.com/NativeScript/nativescript-fresco/wiki/Running-the-'demo'-app) wiki page on the topic of how to run the demo app of the repository.

Closing this thread for now, if you find yourself with more question feel free to write again.
