### ISSUE TITLE
java.lang.NullPointerException: SimpleDraweeView was not initialized

### ISSUE THREAD

**Issue by oluwaseye** [NativeScript/nativescript-fresco#46]
Followed the process of adding it to my project. 
Vanilla JS
Hello world template.

NS version: 3.1.3
Fresco: 3.0.4

Here's a screenshot
![capture2](https://user-images.githubusercontent.com/958447/29315437-47ed69b0-8191-11e7-8d04-f9659b7cf42e.JPG)

**Comment by VladimirAmiorkov** [comment]
Hi @oluwaseye ,

Make sure that the Fresco plugin is initialized as shown in the readme [here](https://github.com/NativeScript/nativescript-fresco#in-vanila-nativescript):

```
import application = require("application");
import fresco = require("nativescript-fresco");

if (application.android) {
    application.onLaunch = function (intent) {
        fresco.initialize();
    };
}

```

**Comment by oluwaseye** [comment]
It was initialized in the app.js like this

```
var application = require("application");
var fresco = require("nativescript-fresco");

if (application.android) {
    application.onLaunch = function (intent) {
        fresco.initialize();
    };
}

```
I am using NS core/ Vanilla JS. Created multiple test projects and came up with the same error.

**Comment by VladimirAmiorkov** [comment]
@oluwaseye Can you try to run the demo app in this repository and let us know if you still have those issues. From the screenshot that you provided the only reason for such error is that the `initialize()` method of the plugin has not been called.
