### ISSUE TITLE
Question: is Fresco still recommended for NS projects?

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/nativescript-fresco#48]
Fresco was made years ago. NS Image now offers async loading and various stretch options. Is Fresco still recommended/needed to provide best user experience with NS 3.2?

**Comment by VladimirAmiorkov** [comment]
Hi @sserdyuk ,

Well this question is still up to debate, Fresco does provide a lot of features that are not available in the default `Image` in NativeScript like failure, placeholder images, "tap to retry download" [etc.](https://github.com/NativeScript/nativescript-fresco#features). On the other hand if you simply want show an image maybe it easier and simpler to use the default `Image` tag. Performance-wise Fresco is still the standard in Android development for a reason but that does not mean that you cannot get the same or better using a different way of managing images, which is what the core modules `Image` tag is doing. Yes we have improved that a lot in the latest versions of NativeScript, my best suggestion I can personally give is "test it", try with and without nativescript-fresco and choose which one is better for you.

**Comment by sserdyuk** [comment]
Just for reference of people that might stumble on this issue looking for an answer, yes, Fresco is indeed still better than the core Image component, and it wasn't hard to integrate into the project.
