### ISSUE TITLE
error in com.facebook.drawee

### ISSUE THREAD

**Issue by cinder92** [NativeScript/nativescript-fresco#5]
Hello i'm receiving this error

`cannot read property 'drawee' of undefined`

in this code

```
if (applicationModule.android) {
    applicationModule.onLaunch = function (intent) {
        com.facebook.drawee.backends.pipeline.Fresco.initialize(applicationModule.android.context);
    };
}
```

**Comment by VladimirAmiorkov** [comment]
Hi @cinder92 ,

I am no longer seeing this issue with the latest update 1.0.0. I will close this issue for now. If you continue to see it please let us know by reopening it.
