### ISSUE TITLE
Binding the path to imageUri not working.!!

### ISSUE THREAD

**Issue by sagar1911** [NativeScript/nativescript-fresco#52]
Hi,
I am trying to display the images which are returned by the nativescript-imagepicker, so I am binding the path to imageUri like this
`<ns-fresco:FrescoDrawee width="{{ itemWidth }}" imageUri="{{ filePath }}"/>`
my filePath looks like this "/storage/emulated/0/DCIM/Camera/IMG_20171215.jpg"

What mistake I am doing here ??

Thanks.

**Comment by NickIliev** [comment]
On what device/emulator you are trying to access this path? Keep in mind that on Android API23 and above, you will need runtime permissions to access files from external storage (apart from the permissions set n the `AndroidManifest.xml`).  If that is the case, you can use [this plugin](https://www.npmjs.com/package/nativescript-permissions) for requiring runtime permissions.

**Comment by sagar1911** [comment]
Hi @NickIliev ,
Thanks for the reply.
I am sauccessfully accesing the images and when I use that path with src attribute in image tag its working fine.
I am using Mi Max 2 device.

**Comment by tgpetrov** [comment]
Hi @sagar1911,

You can't directly use a string with path to an image from the phone's storage. Have a look [here](https://github.com/NativeScript/nativescript-fresco/issues/27) where it is explained how to use the `file-system` module.
