### ISSUE TITLE
Could not resolve com.facebook.fresco:fresco:0.9.0+.

### ISSUE THREAD

**Issue by raghav14** [NativeScript/nativescript-fresco#62]
Could not resolve all dependencies for configuration ':_F0F1F2F3F4F5DebugApkCopy'.
   > Could not resolve com.facebook.fresco:fresco:0.9.0+.
     Required by:
         project :
      > Could not resolve com.facebook.fresco:fresco:0.9.0+.
         > Failed to list versions for com.facebook.fresco:fresco.
            > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/fresco/fresco/maven-metadata.xml.
               > Could not GET 'https://jcenter.bintray.com/com/facebook/fresco/fresco/maven-metadata.xml'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Command ./gradlew failed with exit code 1

Got this issue while running in Nativescript application for android.
For iOS it's working fine.
Even when I tried creating a new project and add this plugin getting same issue.

Will be really helpful if somebody can help on this.

**Comment by VladimirAmiorkov** [comment]
Hi @raghav14 ,

Thank you for contacting us. By the look of the error message and code 403 it looks like your working in an environment which is blocking gradle from downloading the require by Fresco native Android library. Take a look at [this](https://stackoverflow.com/questions/46038496/gradle-received-status-code-403-from-server-forbidden) thread. Can you make sure that you do not have any specific firewalls etc. on your network.
