### ISSUE TITLE
Feature: support resizing and downsampling 

### ISSUE THREAD

**Issue by mintyweazel** [NativeScript/nativescript-fresco#70]
As you all know, the native fresco library supports several [image resizing options](http://frescolib.org/docs/resizing.html).
However, this plugin is not yet exposed the features for a long time.

I have personally extended this plugin for enabling resize and downsampling options of native fresco library, and applied to my nativescript app which manages thousands of image files including jpg,png,and gif. So far, the customized plugin handles the image resizing quite well without any noticeable problems.
 
How do you feel about adding support this feature to nativescript-fresco?
I am ready to contribute to this project if needed.

Thanks in advance.

**Comment by VladimirAmiorkov** [comment]
Hi @mintyweazel ,

Thank you for writing to us and bringing this to our attention. 

Indeed this native functionality has not been exposed in the plugin. We would love to see and welcome any contributions to this or any other nativescript plugin so do not hesitate to make your PR. If you want to make your contribution just submit your PR and we are going to review it, merge it and release a new version of the plugin as soon as possible.

**Comment by VladimirAmiorkov** [comment]
Available in [3.1.0](https://github.com/NativeScript/nativescript-fresco/releases/tag/v3.1.0)
